name: "SWD Deployment Notes"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@v3

      # Setup Node.js 16 with npm caching
      - name: Setup Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build project
      - name: Build project
        run: npm run build

      # Deploy to Netlify
      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: "./build"
          comment-on-commit: false
